### ISSUE TITLE
Problème d'upgrade vers 0.0.5

### ISSUE THREAD

**Issue by kent1D** [AlternC/alternc-certbot#5]
La 0.0.5 ne veut pas s'installer

Voila le message d'erreur :

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  alternc-certbot
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/4554 B of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n]
dpkg-deb: error: parsing file '/tmp/dpkg-deb.RgEYAE/control' near line 2 package 'alternc-certbot':
 error in 'Version' field string '0.0.5-': revision number is empty
Traceback (most recent call last):
  File "/usr/share/apt-listchanges/DebianFiles.py", line 124, in readdeb
    output = subprocess.check_output(command)
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['dpkg-deb', '-f', '/var/cache/apt/archives/alternc-certbot_0.0.5-_all.deb', 'Package', 'Source', 'Version', 'Architecture', 'Status']' returned non-zero exit status 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/apt-listchanges", line 243, in <module>
    main(config)
  File "/usr/bin/apt-listchanges", line 101, in main
    pkg = DebianFiles.Package(deb)
  File "/usr/share/apt-listchanges/DebianFiles.py", line 215, in __init__
    parser.readdeb(self.path)
  File "/usr/share/apt-listchanges/DebianFiles.py", line 128, in readdeb
    {'what': file, 'errmsg': str(ex)}) from ex
NameError: name 'file' is not defined
Preconfiguring packages ...
dpkg: error processing archive /var/cache/apt/archives/alternc-certbot_0.0.5-_all.deb (--unpack):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'alternc-certbot':
 error in 'Version' field string '0.0.5-': revision number is empty
Errors were encountered while processing:
 /var/cache/apt/archives/alternc-certbot_0.0.5-_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by camlafit** [comment]
version ? stretch ?

**Comment by kent1D** [comment]
Oui mais ça marchait bien jusqu'à la 0.0.4, me semble juste un pb de compil bintray non?

**Comment by camlafit** [comment]
Salut

J'ai régénéré la 0.0.5 sur les 2 depots stablet et nightly, est ce mieux ?

**Comment by kent1D** [comment]
Parfait
